// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customCard': string;
  'presetCard': string;
  'presetFolder': string;
  'presetGrid': string;
  'presetName': string;
  'presetType': string;
}
export const cssExports: CssExports;
export default cssExports;
