// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addSystem': string;
  'center': string;
  'systems': string;
}
export const cssExports: CssExports;
export default cssExports;
