import GameSystem from 'GameSystem/GameSystem';

export interface GameSystemPreset extends Omit<GameSystem, 'id' | 'tags'> {
  generation: string;
}

const GAME_SYSTEM_PRESETS: GameSystemPreset[] = [
  // 3rd Generation (8-bit)
  {
    generation: '3rd Generation (8-bit)',
    name: 'Nintendo Entertainment System',
    folderName: 'nes',
    systemType: 0,
    fileExtensions: ['.nes', '.unf', '.unif'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '3rd Generation (8-bit)',
    name: 'Sega Master System',
    folderName: 'mastersystem',
    systemType: 0,
    fileExtensions: ['.sms'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },

  // 4th Generation (16-bit)
  {
    generation: '4th Generation (16-bit)',
    name: 'Super Nintendo',
    folderName: 'snes',
    systemType: 0,
    fileExtensions: ['.sfc', '.smc'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '4th Generation (16-bit)',
    name: 'Sega Genesis / Mega Drive',
    folderName: 'megadrive',
    systemType: 0,
    fileExtensions: ['.md', '.gen', '.bin', '.smd'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '4th Generation (16-bit)',
    name: 'Game Boy',
    folderName: 'gb',
    systemType: 0,
    fileExtensions: ['.gb'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },

  // 5th Generation (32/64-bit)
  {
    generation: '5th Generation (32/64-bit)',
    name: 'Sony PlayStation',
    folderName: 'psx',
    systemType: 0,
    fileExtensions: ['.bin', '.cue', '.iso', '.chd', '.pbp'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '5th Generation (32/64-bit)',
    name: 'Nintendo 64',
    folderName: 'n64',
    systemType: 0,
    fileExtensions: ['.z64', '.n64', '.v64'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '5th Generation (32/64-bit)',
    name: 'Sega Saturn',
    folderName: 'saturn',
    systemType: 0,
    fileExtensions: ['.bin', '.cue', '.iso', '.chd'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '5th Generation (32/64-bit)',
    name: 'Game Boy Advance',
    folderName: 'gba',
    systemType: 0,
    fileExtensions: ['.gba'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },

  // 6th Generation
  {
    generation: '6th Generation',
    name: 'Sony PlayStation 2',
    folderName: 'ps2',
    systemType: 0,
    fileExtensions: ['.iso', '.bin', '.chd'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '6th Generation',
    name: 'Nintendo GameCube',
    folderName: 'gamecube',
    systemType: 0,
    fileExtensions: ['.iso', '.gcz', '.rvz', '.nkit.iso'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '6th Generation',
    name: 'Sega Dreamcast',
    folderName: 'dreamcast',
    systemType: 0,
    fileExtensions: ['.gdi', '.cdi', '.chd'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },

  // 7th Generation
  {
    generation: '7th Generation',
    name: 'Nintendo Wii',
    folderName: 'wii',
    systemType: 0,
    fileExtensions: ['.iso', '.wbfs', '.rvz', '.nkit.iso'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '7th Generation',
    name: 'Sony PlayStation 3',
    folderName: 'ps3',
    systemType: 1,
    fileExtensions: ['.iso', '.pkg'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '{Game Title} v{Version}.{Extension}',
    dlcNamingFormat: '{Game Title} DLC{Index}.{Extension}',
    baseFolderName: 'base',
    updateFolderName: 'update',
    dlcFolderName: 'dlc',
  },
  {
    generation: '7th Generation',
    name: 'Sony PlayStation Portable',
    folderName: 'psp',
    systemType: 0,
    fileExtensions: ['.iso', '.cso', '.pbp'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: '7th Generation',
    name: 'Nintendo DS',
    folderName: 'nds',
    systemType: 0,
    fileExtensions: ['.nds'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },

  // 8th Generation
  {
    generation: '8th Generation',
    name: 'Nintendo Wii U',
    folderName: 'wiiu',
    systemType: 1,
    fileExtensions: ['.wua', '.wud', '.wux', '.rpx'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '{Game Title} v{Version}.{Extension}',
    dlcNamingFormat: '{Game Title} DLC{Index}.{Extension}',
    baseFolderName: 'base',
    updateFolderName: 'update',
    dlcFolderName: 'dlc',
  },
  {
    generation: '8th Generation',
    name: 'Nintendo 3DS',
    folderName: '3ds',
    systemType: 1,
    fileExtensions: ['.3ds', '.cia'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '{Game Title} v{Version}.{Extension}',
    dlcNamingFormat: '{Game Title} DLC{Index}.{Extension}',
    baseFolderName: 'base',
    updateFolderName: 'update',
    dlcFolderName: 'dlc',
  },
  {
    generation: '8th Generation',
    name: 'Sony PlayStation Vita',
    folderName: 'psvita',
    systemType: 1,
    fileExtensions: ['.vpk', '.mai'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '{Game Title} v{Version}.{Extension}',
    dlcNamingFormat: '{Game Title} DLC{Index}.{Extension}',
    baseFolderName: 'base',
    updateFolderName: 'update',
    dlcFolderName: 'dlc',
  },

  // 9th Generation / Current
  {
    generation: '9th Generation / Current',
    name: 'Nintendo Switch',
    folderName: 'switch',
    systemType: 1,
    fileExtensions: ['.nsp', '.nsz', '.xci', '.xcz'],
    namingFormat: '{Game Title} {Region}.{Extension}',
    updateNamingFormat: '{Game Title} v{Version}.{Extension}',
    dlcNamingFormat: '{Game Title} DLC{Index}.{Extension}',
    baseFolderName: 'base',
    updateFolderName: 'update',
    dlcFolderName: 'dlc',
  },

  // PC
  {
    generation: 'PC',
    name: 'DOS',
    folderName: 'dos',
    systemType: 0,
    fileExtensions: ['.exe', '.com', '.bat'],
    namingFormat: '{Game Title}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
  {
    generation: 'PC',
    name: 'ScummVM',
    folderName: 'scummvm',
    systemType: 0,
    fileExtensions: ['.scummvm'],
    namingFormat: '{Game Title}.{Extension}',
    updateNamingFormat: '',
    dlcNamingFormat: '',
    baseFolderName: '',
    updateFolderName: '',
    dlcFolderName: '',
  },
];

export default GAME_SYSTEM_PRESETS;
