// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cloneButton': string;
  'enabled': string;
  'gameSystem': string;
  'name': string;
  'nameContainer': string;
  'systemIcon': string;
  'topRight': string;
}
export const cssExports: CssExports;
export default cssExports;
