enum CommandNames {
  ApplicationUpdate = 'ApplicationUpdate',
  Backup = 'Backup',
  ClearBlocklist = 'ClearBlocklist',
  ClearLog = 'ClearLog',
  CutoffUnmetFileSearch = 'CutoffUnmetRomSearch',
  DeleteLogFiles = 'DeleteLogFiles',
  DeleteUpdateLogFiles = 'DeleteUpdateLogFiles',
  DownloadedFilesScan = 'DownloadedFilesScan',
  FileSearch = 'RomSearch',
  ManualImport = 'ManualImport',
  MissingFileSearch = 'MissingRomSearch',
  MoveGame = 'MoveGame',
  RefreshMonitoredDownloads = 'RefreshMonitoredDownloads',
  RefreshSeries = 'RefreshSeries',
  RenameFiles = 'RenameFiles',
  RenameSeries = 'RenameSeries',
  ResetApiKey = 'ResetApiKey',
  ResetQualityDefinitions = 'ResetQualityDefinitions',
  RssSync = 'RssSync',
  SeasonSearch = 'SeasonSearch',
  SeriesSearch = 'SeriesSearch',
}

export default CommandNames;
