// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailsIcon': string;
  'folder': string;
  'game': string;
  'gameType': string;
  'monitor': string;
  'platformFolder': string;
  'qualityProfile': string;
}
export const cssExports: CssExports;
export default cssExports;
