// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'downloaded': string;
  'entryCount': string;
  'name': string;
  'notDownloaded': string;
  'size': string;
  'source': string;
  'status': string;
  'system': string;
}
export const cssExports: CssExports;
export default cssExports;
