// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dlcList': string;
  'missing': string;
  'orphanWarning': string;
  'patchInfo': string;
  'patchInfoHeader': string;
  'patchLabel': string;
  'patchRow': string;
  'present': string;
  'version': string;
}
export const cssExports: CssExports;
export default cssExports;
