// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allRoms': string;
  'info': string;
  'platform': string;
  'roms': string;
}
export const cssExports: CssExports;
export default cssExports;
