// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'platforms': string;
  'truncated': string;
}
export const cssExports: CssExports;
export default cssExports;
