// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionCell': string;
  'autoMatchProgress': string;
  'cell': string;
  'checkboxCell': string;
  'clearMatchButton': string;
  'fileDetails': string;
  'filesCell': string;
  'footer': string;
  'footerLeft': string;
  'header': string;
  'headerCell': string;
  'identifyIgdbId': string;
  'identifyInfo': string;
  'identifyInput': string;
  'identifyOverview': string;
  'identifyPoster': string;
  'identifyPosterImage': string;
  'identifyPosterPlaceholder': string;
  'identifyResultRow': string;
  'identifyResults': string;
  'identifySearch': string;
  'identifyTitle': string;
  'identifyYear': string;
  'importingSpinner': string;
  'matchCell': string;
  'matchCount': string;
  'matchToolbar': string;
  'matchedBadge': string;
  'nameCell': string;
  'pathInput': string;
  'resultError': string;
  'resultSuccess': string;
  'resultsSection': string;
  'row': string;
  'scanSection': string;
  'selectedCount': string;
  'sizeCell': string;
  'systemBadge': string;
  'systemCell': string;
  'table': string;
  'typeCell': string;
  'unmatchedBadge': string;
}
export const cssExports: CssExports;
export default cssExports;
