// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'name': string;
  'overlay': string;
  'provider': string;
  'providers': string;
  'underlay': string;
}
export const cssExports: CssExports;
export default cssExports;
