// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addProvider': string;
  'center': string;
  'providers': string;
}
export const cssExports: CssExports;
export default cssExports;
